### ISSUE TITLE
some information

### ISSUE THREAD

**Issue by totos21** [BwanaFr/pibooth-ledstrip#1]
hello
I search to install your plugin but I don't know how to install it and the wiring schema. 

Could you please tell me these informations ? 

many thanks

regards

**Comment by BwanaFr** [comment]
Hello,

I need to do some documentation.
I'll do it in next days and let you know.

Thanks!

**Comment by totos21** [comment]
thanks 🙏

**Comment by totos21** [comment]
I allow myself to revive the subject because I would like to wire my led strip. thanks in advance. Regards,

**Comment by totos21** [comment]
Hello

could you tell me where I find PIN number which I can plug my led strip din ? 

thanks

**Comment by BwanaFr** [comment]
Please be patient. I don't have time right now.
I've to remind what I made...

**Comment by BwanaFr** [comment]
What kind of LED strips do you have?
I only support ws2801 based led strips....

**Comment by totos21** [comment]
I use ws2812b led strip. Is the same ?

**Comment by BwanaFr** [comment]
ws2812b is not supported by my plugin (I used SPI and the adafruit_circuitpython-ws2801 library).
ws2812b interface is different. Maybe the plugin can be improved for supporting ws2812b but it's not in my plan.
